### ISSUE TITLE
Doesn't work with jekyll 1.0

### ISSUE THREAD

**Issue by nebiros** [plusjade/jekyll-bootstrap#155]
jekyll 1.0 is released, http://blog.parkermoore.de/2013/05/06/jekyll-1-dot-0-released, so I update the gem and I got this error:

```
$ jekyll serve
Configuration file: /Users/nebiros/Dropbox/Projects/nebiros.github.com/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --watch/-w command-line option instead.
            Source: /Users/nebiros/Dropbox/Projects/nebiros.github.com
       Destination: /Users/nebiros/Dropbox/Projects/nebiros.github.com/_site
      Generating...   Liquid Exception: undefined method `sub' for nil:NilClass in 2013-01-31-entityforname-could-not-locate-an-nsmanagedobjectmodel-for-entity-name.md
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/tags/highlight.rb:77:in `add_code_tags'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/tags/highlight.rb:57:in `render_pygments'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/tags/highlight.rb:45:in `render'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:106:in `block in render_all'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:93:in `each'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:93:in `render_all'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/block.rb:82:in `render'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/template.rb:124:in `render'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/liquid-2.5.0/lib/liquid/template.rb:132:in `render!'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/convertible.rb:77:in `render_liquid'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/convertible.rb:128:in `do_layout'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/post.rb:285:in `render'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/site.rb:230:in `block in render'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/site.rb:229:in `each'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/site.rb:229:in `render'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/site.rb:44:in `process'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/command.rb:18:in `process_site'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/commands/build.rb:23:in `build'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/lib/jekyll/commands/build.rb:7:in `process'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/jekyll-1.0.0/bin/jekyll:83:in `block (2 levels) in <top (required)>'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/command.rb:155:in `run'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/runner.rb:66:in `run!'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/delegates.rb:11:in `run!'
/Users/nebiros/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
Build Failed
```
